=== julioruizhidalgo/Ditaproject_julio/Project_1.dtd
<?xml version="1.0" encoding="UTF-8"?>



<!ELEMENT Agency_report (to, name, date, city,address, body, website)>
<!ELEMENT to (#PCDATA) >
<!ELEMENT name (#PCDATA)>
<!ELEMENT date (#PCDATA) >
<!ELEMENT city (#PCDATA) >
<!ELEMENT address (#PCDATA)>
<!ELEMENT body (employee,employee,employee,employee,employee?,employee?,employee?, tour,tour,tour+, Finance_Report)>
<!-- I dont know how to add 4-7 employees? Answer: use "?" -->
<!ELEMENT website (#PCDATA) >
<!ATTLIST date day (1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31) #REQUIRED>
<!ATTLIST date month (January|February|March|April|May|June|July|August|September|October|November|December) #REQUIRED>

<!ELEMENT Finance_Report (fullYear+,fullSeason+) >
<!ELEMENT fullYear (trip*, income )>
<!ELEMENT fullSeason (trip*, income )>
<!ATTLIST fullSeason seasonName CDATA #IMPLIED>
<!ELEMENT income (#PCDATA)>

<!ELEMENT trip (customer,customer,customer+) >
<!ATTLIST trip tripname IDREF #REQUIRED>
<!-- I still do not know how to reference tour_name -->
<!ELEMENT customer (name, age) >
<!ATTLIST customer gender (male|female) #IMPLIED >

<!ATTLIST fullSeason ticket_only CDATA #IMPLIED >
<!ATTLIST fullYear ticket_only CDATA #IMPLIED >




<!ELEMENT employee (name, age, salary)>
<!-- name is defined at the beginning. Is that alright or do we need to repeat it? -->
<!ELEMENT age (#PCDATA) >
<!ELEMENT salary (#PCDATA) >

<!ATTLIST employee tittle (officer|manager|clerck|secretary|tour_leader) "officer">
<!ATTLIST employee staff_id ID #REQUIRED>

<!ATTLIST salary mode (weekly|monthly) #REQUIRED >
<!ATTLIST salary currency CDATA #FIXED "EUR">

<!ELEMENT tour (destination, leader, leader?, price, date)>
<!ATTLIST tour type (domestic|international) #REQUIRED >
<!ATTLIST tour mode_transport (bus|cruise|air|train) #REQUIRED >
<!ATTLIST tour tour_name ID #REQUIRED >

<!ELEMENT destination (country, city)>
<!ELEMENT country (#PCDATA) >
<!ELEMENT leader (name) >
<!ATTLIST leader leaderID IDREF #REQUIRED >
<!-- IDREF says that there is a reference. Dont we need to add  what it is referrencing to? -->

<!ELEMENT price (#PCDATA)>

<!-- Entities list -->

<!ENTITY total-tours "The total number of sold tour packages from our office has shown" >
<!ENTITY website "www.myTravelAgency.org">
<!ENTITY recipient "To whom it may concerns" >
<!ENTITY sign "Your sincerely: Cork branch." >

=== julioruizhidalgo/Ditaproject_julio/Project_1_scenario_2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Agency_report SYSTEM "Project_1.dtd">

<Agency_report>
    <to></to>
    <name></name>
    <date day="4" month="January"></date>
    <city>Barcelona</city>
    <address>XXXXXX</address>
    <body>
        <employee staff_id="pnp_3fg_ljb">
            <name>Julio</name>
            <age>20</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="it2_kfg_ljb">
            <name>Victoria</name>
            <age>22</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="f3n_lfg_ljb">
            <name>Luis</name>
            <age></age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="xhm_mfg_ljb">
            <name>Angela</name>
            <age>30</age>
            <salary mode="monthly"></salary>
        </employee>
        <tour type="international" mode_transport="air" tour_name="t2x_wfg_ljb">
            <destination>
                <country>France</country>
                <city>Montpelier</city>
            </destination>
            <leader leaderID="pnp_3fg_ljb">
                <name>Julio</name>
            </leader>
            <price>100</price>
            <date day="3" month="May"></date>
        </tour>
        <tour type="international" mode_transport="cruise" tour_name="oyd_zfg_ljb">
            <destination>
                <country>Spain</country>
                <city>Ibiza</city>
            </destination>
            <leader leaderID="f3n_lfg_ljb">
                <name>Luis</name>
            </leader>
            <price>2000</price>
            <date day="7" month="August"></date>
        </tour>
        <tour type="international" mode_transport="air" tour_name="shd_2gg_ljb">
            <destination>
                <country>UK</country>
                <city>London</city>
            </destination>
            <leader leaderID="xhm_mfg_ljb">
                <name>Angela</name>
            </leader>
            <price>500</price>
            <date day="10" month="October"></date>
        </tour>
        <tour type="domestic" mode_transport="train" tour_name="ir2_jgg_ljb">
            <destination>
                <country>Ireland</country>
                <city>Dublin</city>
            </destination>
            <leader leaderID="f3n_lfg_ljb">
                <name>Luis</name>
            </leader>
            <leader leaderID="it2_kfg_ljb">
                <name>Victoria</name>
            </leader>
            <price>300</price>
            <date day="7" month="February"></date>
        </tour>
        <tour type="domestic" mode_transport="bus" tour_name="bnv_pgg_ljb">
            <destination>
                <country>Northern Ireland</country>
                <city>Belfast</city>
            </destination>
            <leader leaderID="xhm_mfg_ljb">
                <name>Angela</name>
            </leader>
            <leader leaderID="it2_kfg_ljb">
                <name>Victoria</name>
            </leader>
            <price>600</price>
            <date day="8" month="April"></date>
        </tour>
        <Finance_Report>
            <fullYear ticket_only="1">
                <trip tripname="t2x_wfg_ljb">
                    <customer>
                        <name>Juana</name>
                        <age>40</age>
                    </customer>
                    <customer>
                        <name>Ana</name>
                        <age>45</age>
                    </customer>
                    <customer>
                        <name>Amelia</name>
                        <age>44</age>
                    </customer>
                    <customer>
                        <name>Antonia</name>
                        <age>50</age>
                    </customer>
                </trip>
                <income>xxxxxx</income>
            </fullYear>
            <fullYear>
                <trip tripname="bnv_pgg_ljb">
                    <customer>
                        <name>Alfonsa</name>
                        <age>18</age>
                    </customer>
                    <customer>
                        <name>Santiaga</name>
                        <age>18</age>
                    </customer>
                    <customer>
                        <name>Rogelia</name>
                        <age>19</age>
                    </customer>
                </trip>
                <trip tripname="shd_2gg_ljb">
                    <customer>
                        <name>Lolo</name>
                        <age>25</age>
                    </customer>
                    <customer>
                        <name>Lola</name>
                        <age>23</age>
                    </customer>
                    <customer>
                        <name>Lulu</name>
                        <age>30</age>
                    </customer>
                </trip>
                <income></income>
            </fullYear>
            <fullSeason seasonName="Spring">
                <trip tripname="shd_2gg_ljb">
                    <customer>
                        <name>Coco</name>
                        <age>20</age>
                    </customer>
                    <customer>
                        <name>Pepe</name>
                        <age>20</age>
                    </customer>
                    <customer>
                        <name>Paco</name>
                        <age>20</age>
                    </customer>
                    <customer>
                        <name>Lola</name>
                        <age>20</age>
                    </customer>
                </trip>
                <trip tripname="bnv_pgg_ljb">
                    <customer>
                        <name>Coco</name>
                        <age>20</age>
                    </customer>
                    <customer>
                        <name>Paco</name>
                        <age>26</age>
                    </customer>
                    <customer>
                        <name>Manu</name>
                        <age>30</age>
                    </customer>
                    <customer>
                        <name>Lola</name>
                        <age>20</age>
                    </customer>
                </trip>
                <trip tripname="ir2_jgg_ljb">
                    <customer>
                        <name>Juan</name>
                        <age>30</age>
                    </customer>
                    <customer>
                        <name>Juana</name>
                        <age>32</age>
                    </customer>
                    <customer>
                        <name>Juanloa</name>
                        <age>23</age>
                    </customer>
                    <customer>
                        <name>Lola</name>
                        <age>20</age>
                    </customer>
                </trip>
                
                <income>XXXXXXXX</income>
            </fullSeason>
        </Finance_Report>
    </body>
    <website>&website;</website>
</Agency_report>

=== julioruizhidalgo/Ditaproject_julio/Project_1_scenario_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Agency_report SYSTEM "Project_1.dtd">

<Agency_report>
    <to>
        &recipient;
    </to>
    <name></name>
    <date day="1" month="January"></date>
    <city></city>
    <address></address>
    <body>
        <employee staff_id="mvs_zs4_jjb">
            <name>Julio</name>
            <age> 20</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="ly5_ct4_jjb">
            <name>Ana</name>
            <age> 22</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="tvv_2t4_jjb">
            <name>Agustina</name>
            <age> 25</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="jb3_ht4_jjb">
            <name>Felipa</name>
            <age> 21</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="ec1_jt4_jjb">
            <name>Raimunda</name>
            <age> 22</age>
            <salary mode="monthly"></salary>
        </employee>
        <employee staff_id="fkj_lt4_jjb">
            <name>Ofelio</name>
            <age> 19</age>
            <salary mode="monthly"></salary>
        </employee>
        <tour mode_transport="air" tour_name="bdv_h54_jjb" type="international">
            <destination>
                <country>Ireland</country>
                <city>Dublin</city>
            </destination>           
            <leader leaderID="mvs_zs4_jjb">
                <name>Julio</name>                          
            </leader>
            <price>10</price>
            <date day="11" month="April"></date>
        </tour>
        <tour mode_transport="cruise" tour_name="kfs_l54_jjb" type="international">
            <destination>
                <country>France</country>
                <city>Nize</city>
            </destination>
            <leader leaderID="mvs_zs4_jjb">
                <name>Julio</name>
             
            </leader >
            <leader leaderID="ly5_ct4_jjb">
                <name>Ana</name>
            </leader>
            <price>1000</price>
            <date day="12" month="July"></date>
        </tour>
        <tour mode_transport="bus" tour_name="cjq_dv4_jjb" type="domestic">
            <destination>
                <country>Spain</country>
                <city>Aranjuez</city>
            </destination>
            <leader leaderID="ly5_ct4_jjb">
                <name>Ana</name>
            </leader>
            <price>500</price>
            <date day="10" month="April"></date>
        </tour>
        <tour mode_transport="train" tour_name="p2b_mv4_jjb" type="domestic">
            <destination>
                <country>Spain</country>
                <city>Bilbao</city>
            </destination>
            <leader leaderID="ly5_ct4_jjb">
                <name>Ana</name>
            </leader>
            <leader leaderID="mvs_zs4_jjb">
                <name>Julio</name>
            </leader>
            <price>600</price>
            <date day="15" month="November"></date>
        </tour>
        <Finance_Report>
            <fullYear>
                <trip tripname="bdv_h54_jjb">
                    <customer>
                        <name> Pepe</name>
                        <age>30</age>
                    </customer>
                    <customer>
                        <name>Pepa</name>
                        <age>32</age>
                    </customer>
                    <customer>
                        <name>Pepito</name>
                        <age>15</age>
                    </customer>
                    <customer>
                        <name>Pepita</name>
                        <age>12</age>
                    </customer>
                </trip>
                <trip tripname="bdv_h54_jjb">
                    <customer>
                        <name>Juan</name>
                        <age>40</age>
                    </customer>
                    <customer>
                        <name>Juana</name>
                        <age>38</age>
                    </customer>
                    <customer>
                        <name>Juanito</name>
                        <age>20</age>
                    </customer>
                    <customer>
                        <name>Juanita</name>
                        <age>22</age>
                    </customer>
                </trip>
                <income>xxxxxx</income>
            </fullYear>
            <fullSeason ticket_only="1">
                <trip tripname="bdv_h54_jjb" >
                    <customer gender="female">
                        <name>Ana</name>
                        <age>25</age>
                    </customer>
                    <customer gender="female">
                        <name>Lucia</name>
                        <age>25</age>
                    </customer>
                    <customer gender="female">
                        <name>Valeria</name>
                        <age>25</age>
                    </customer>
                    
                </trip>
                <income>XXXXXXXX</income>
            </fullSeason>
            <fullSeason>
                <trip tripname="cjq_dv4_jjb">
                    <customer>
                        <name>Antonio</name>
                        <age>34</age>
                    </customer>
                    <customer>
                        <name>Alberto</name>
                        <age>34</age>
                    </customer>
                    <customer>
                        <name>Anna</name>
                        <age>25</age>
                    </customer>
                    <customer>
                        <name>Neto</name>
                        <age>30</age>
                    </customer>
                </trip>
                <trip tripname="cjq_dv4_jjb">
                    <customer>
                        <name>Maria</name>
                        <age>50</age>
                    </customer>
                    <customer>
                        <name>Felix</name>
                        <age>49</age>
                    </customer>
                    <customer>
                        <name>Santiaga</name>
                        <age>52</age>
                    </customer>
                    <customer>
                        <name>Neta</name>
                        <age>55</age>
                    </customer>
                    
                </trip>
                <income>xxxxxxx</income>
            </fullSeason>
            <fullSeason seasonName="Winter" ticket_only="2">
                <trip tripname="kfs_l54_jjb" >
                    <customer>
                        <name>Amaparo</name>
                        <age>22</age>
                    </customer>
                    <customer>
                        <name>Alexia</name>
                        <age>25</age>
                    </customer>
                    <customer>
                        <name>Lia</name>
                        <age>30</age>
                    </customer>
                    <customer>
                        <name>Lolo</name>
                        <age>34</age>
                    </customer>
                    <customer>
                        <name>Jose</name>
                        <age>32</age>
                    </customer>
                   
                </trip>
                
                <trip tripname="p2b_mv4_jjb">
                    <customer>
                        <name>Amaparo</name>
                        <age>22</age>
                    </customer>
                    <customer>
                        <name>Alexia</name>
                        <age>25</age>
                    </customer>
                    <customer>
                        <name>Lia</name>
                        <age>30</age>
                    </customer>
                    <customer>
                        <name>Lolo</name>
                        <age>34</age>
                    </customer>
                    <customer>
                        <name>Jose</name>
                        <age>32</age>
                    </customer>
                </trip>
                <income> xxxxxxx</income>
                
            </fullSeason>
        </Finance_Report>
    </body>
    <website></website>
    
</Agency_report>
